name: Build and deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Prepare environment
        uses: actions/setup-node@v4
        with:
          node-version: "20" # use Node.js 20 (LTS)

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9 

      - name: Install deps
        run: pnpm install

      - name: Build plugin(s)
        run: node ./build.mjs

      # Foolproof feature:
      # - Copies over README so that the root of the deployed website shows it
      # - Changes 404 page to README so that you don't get lost while clicking links
      - name: Copy additional files
        run: |
          cp README.md dist/README.md
          printf -- "---\npermalink: /404.html\n---\n" > dist/404.md
          printf -- "> **Note:** You accessed a link that returned a 404, probably by clicking one of the plugin links. You're supposed to copy the link address and add it into Vendetta.\n\n" >> dist/404.md
          cat README.md >> dist/404.md

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          enable_jekyll: true
          # cname: example.com
